In [2]:
import pandas as pd

titanic = pd.read_csv("../exercice_08/data/titanic_propre.csv")
titanic.shape

(784, 15)

In [3]:
survie_par_classe_et_sexe = titanic.groupby(["class", "sex"])["survived"].mean().round(2)
survie_par_classe_et_sexe

class   sex
First   female    0.97
        male      0.37
Second  female    0.92
        male      0.18
Third   female    0.47
        male      0.16
Name: survived, dtype: float64

In [4]:
pd.pivot_table(titanic, values="survived", index="class", columns="sex", aggfunc="mean").round(2)

sex     female  male
class
First     0.97  0.37
Second    0.92  0.18
Third     0.47  0.16

In [5]:
titanic["tranche_age"] = pd.cut(
    titanic["age"], bins=[0, 12, 18, 60, 100],
    labels=["enfant", "ado", "adulte", "senior"],
)
survie_par_tranche_age = titanic.groupby("tranche_age")["survived"].mean().round(2)
survie_par_tranche_age

tranche_age
enfant    0.57
ado       0.45
adulte    0.40
senior    0.23
Name: survived, dtype: float64

In [6]:
prix_moyen_par_port = titanic.groupby("embark_town")["fare"].mean().round(2)
prix_moyen_par_port

embark_town
Cherbourg      63.71
Queenstown     14.56
Southampton    28.73
Name: fare, dtype: float64

In [7]:
repartition_classes_par_port = pd.crosstab(
    titanic["embark_town"], titanic["class"], normalize="index"
).round(2)
repartition_classes_par_port

class        First  Second  Third
embark_town
Cherbourg     0.54    0.11   0.35
Queenstown    0.03    0.05   0.92
Southampton   0.22    0.26   0.52

In [8]:
survie_seul_ou_non = titanic.groupby("alone")["survived"].mean().round(2)
survie_seul_ou_non

alone
False    0.51
True     0.34
Name: survived, dtype: float64

In [9]:
titanic["alone"] = (titanic["sibsp"] + titanic["parch"]) == 0

Q1 : Oui. En 1re classe, les femmes ont un taux de survie de 97 %, contre 37 % pour les hommes. Même constat en 2e et 3e classe.

Q2 : Les enfants ont un taux de survie de 57%, contre 40% pour les adultes. Ils ont donc été prioritaires.

Q3 : Le port le plus cher est Cherbourg (prix moyen 63.71). La répartition des classes l'explique en partie par le fait que : 54 % des passagers de ce port voyageaient en 1re classe.

Q4 : Les passagers seuls ont un taux de survie de 34 %, contre 51 % pour les autres. Donc voyager seul diminuait les chances de survie.